#!/bin/bash

echo "🔧 AWS CLI Configuration Helper"
echo "================================"
echo ""
echo "After creating your IAM user, you'll have:"
echo "- Access Key ID (starts with AKIA...)"
echo "- Secret Access Key (long random string)"
echo ""
echo "Run this when you have your credentials:"
echo ""
echo "aws configure"
echo ""
echo "Enter the following when prompted:"
echo "- AWS Access Key ID: [Your Access Key from IAM]"
echo "- AWS Secret Access Key: [Your Secret Key from IAM]"
echo "- Default region name: us-east-1"
echo "- Default output format: json"
echo ""
echo "Then test with:"
echo "aws sts get-caller-identity"
echo ""
echo "Finally, deploy your app:"
echo "./deploy.sh aws prod"
echo ""
echo "🎉 You'll have a fully deployed serverless app!"
