name: Vercel Deployment

on:
  push:
    branches: [ main, master ]
  pull_request:
    branches: [ main, master ]

jobs:
  test:
    runs-on: ubuntu-latest
    
    steps:
    - uses: actions/checkout@v4
    
    - name: Setup Node.js
      uses: actions/setup-node@v4
      with:
        node-version: '18'
        cache: 'yarn'
    
    - name: Install Backend Dependencies
      run: |
        cd backend
        yarn install --frozen-lockfile
    
    - name: Install Frontend Dependencies
      run: |
        cd frontend
        yarn install --frozen-lockfile
    
    - name: Run Backend Tests
      run: |
        cd backend
        yarn test
    
    - name: Run Frontend Tests
      run: |
        cd frontend
        yarn test --watchAll=false --passWithNoTests
    
    - name: Build Backend
      run: |
        cd backend
        yarn build
    
    - name: Build Frontend
      run: |
        cd frontend
        yarn build

  deploy:
    needs: test
    runs-on: ubuntu-latest
    if: github.ref == 'refs/heads/main' || github.ref == 'refs/heads/master'
    
    steps:
    - uses: actions/checkout@v4
    
    - name: Setup Node.js
      uses: actions/setup-node@v4
      with:
        node-version: '18'
        cache: 'yarn'
    
    - name: Install Vercel CLI
      run: yarn global add vercel@latest
    
    - name: Pull Vercel Environment Information
      run: vercel pull --yes --environment=production --token=${{ secrets.VERCEL_TOKEN }}
    
    - name: Build Project Artifacts
      run: vercel build --prod --token=${{ secrets.VERCEL_TOKEN }}
    
    - name: Deploy Project Artifacts to Vercel
      run: vercel deploy --prebuilt --prod --token=${{ secrets.VERCEL_TOKEN }}
